<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PropertySeeder extends Seeder
{
    public function run()
    {
        $properties = [
            // First pair with same province and district
            [
                'name' => 'Property 1',
                'price' => 1000000.00,
                'category' => 'Residential',
                'cluster_type' => 'Cluster A',
                'province' => 'Lampung',
                'regency' => 'Lampung Tengah',
                'district' => 'Terbanggi Besar',
                'village' => 'Yukum Jaya',
                'location' => 'Location 1',
                'toilet' => 2,
                'bedroom' => 3,
                'surface_area' => 100,
                'building_area' => 80,
                'carport' => 1,
                'floor' => 2,
                'description' => 'Description 1',
                'mosque' => true,
                'jogging' => true,
                'sports' => false,
                'child' => false,
                'pool' => true,
                'instalment' => 10000.00,
                'picture' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Property 2',
                'price' => 1530000.00,
                'category' => 'Commercial',
                'cluster_type' => 'Cluster A',
                'province' => 'Lampung',
                'regency' => 'Lampung Tengah',
                'district' => 'Terbanggi Besar',
                'village' => 'Yukum Jaya',
                'location' => 'Location 2',
                'toilet' => 1,
                'bedroom' => 2,
                'surface_area' => 150,
                'building_area' => 120,
                'carport' => 2,
                'floor' => 1,
                'description' => 'Description 2',
                'mosque' => false,
                'jogging' => false,
                'sports' => true,
                'child' => true,
                'pool' => false,
                'instalment' => 15000.00,
                'picture' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            // Second pair with same province and district
            [
                'name' => 'Property 3',
                'price' => 2000000.00,
                'category' => 'Residential',
                'cluster_type' => 'Cluster B',
                'province' => 'Jawa Tengah',
                'regency' => 'Semarang',
                'district' => 'Bojonegoro',
                'village' => 'Bulungan',
                'location' => 'Location 3',
                'toilet' => 2,
                'bedroom' => 4,
                'surface_area' => 200,
                'building_area' => 150,
                'carport' => 1,
                'floor' => 2,
                'description' => 'Description 3',
                'mosque' => true,
                'jogging' => true,
                'sports' => false,
                'child' => true,
                'pool' => false,
                'instalment' => 20000.00,
                'picture' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Property 4',
                'price' => 2500000.00,
                'category' => 'Commercial',
                'cluster_type' => 'Cluster B',
                'province' => 'Lampung Selatan',
                'regency' => 'Way Huwi',
                'district' => 'Way Wawai',
                'village' => 'Indonesia',
                'location' => 'Location 4',
                'toilet' => 3,
                'bedroom' => 3,
                'surface_area' => 250,
                'building_area' => 200,
                'carport' => 2,
                'floor' => 1,
                'description' => 'Description 4',
                'mosque' => false,
                'jogging' => false,
                'sports' => true,
                'child' => false,
                'pool' => true,
                'instalment' => 25000.00,
                'picture' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            // Third pair with same province and district
            [
                'name' => 'Property 5',
                'price' => 300000.00,
                'category' => 'Residential',
                'cluster_type' => 'Cluster C',
                'province' => 'Lampung Selatan',
                'regency' => 'Way Huwi',
                'district' => 'Way Wawai',
                'village' => 'Indonesia',
                'location' => 'Location 5',
                'toilet' => 1,
                'bedroom' => 3,
                'surface_area' => 300,
                'building_area' => 250,
                'carport' => 1,
                'floor' => 2,
                'description' => 'Description 5',
                'mosque' => true,
                'jogging' => false,
                'sports' => false,
                'child' => true,
                'pool' => false,
                'instalment' => 30000.00,
                'picture' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Property 6',
                'price' => 350000.00,
                'category' => 'Commercial',
                'cluster_type' => 'Cluster C',
                'province' => 'Jawa Tengah',
                'regency' => 'Semarang',
                'district' => 'Bojonegoro',
                'village' => 'Bulungan',
                'location' => 'Location 6',
                'toilet' => 2,
                'bedroom' => 2,
                'surface_area' => 350,
                'building_area' => 300,
                'carport' => 2,
                'floor' => 1,
                'description' => 'Description 6',
                'mosque' => false,
                'jogging' => true,
                'sports' => true,
                'child' => false,
                'pool' => true,
                'instalment' => 35000.00,
                'picture' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            // Fourth pair with same province and district
            [
                'name' => 'Property 7',
                'price' => 4000000.00,
                'category' => 'Residential',
                'cluster_type' => 'Cluster D',
                'province' => 'Jawa Barat',
                'regency' => 'Bandung',
                'district' => 'Cimahi',
                'village' => 'Cisair',
                'location' => 'Location 7',
                'toilet' => 2,
                'bedroom' => 4,
                'surface_area' => 400,
                'building_area' => 350,
                'carport' => 1,
                'floor' => 2,
                'description' => 'Description 7',
                'mosque' => true,
                'jogging' => false,
                'sports' => true,
                'child' => true,
                'pool' => false,
                'instalment' => 40000.00,
                'picture' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Property 8',
                'price' => 4500000.00,
                'category' => 'Commercial',
                'cluster_type' => 'Cluster D',
                'province' => 'Jawa Barat',
                'regency' => 'Bandung',
                'district' => 'Cimahi',
                'village' => 'Cisair',
                'location' => 'Location 8',
                'toilet' => 3,
                'bedroom' => 2,
                'surface_area' => 450,
                'building_area' => 400,
                'carport' => 2,
                'floor' => 1,
                'description' => 'Description 8',
                'mosque' => false,
                'jogging' => true,
                'sports' => false,
                'child' => false,
                'pool' => true,
                'instalment' => 45000.00,
                'picture' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            // Fifth pair with same province and district
            [
                'name' => 'Property 9',
                'price' => 5000000.00,
                'category' => 'Residential',
                'cluster_type' => 'Cluster E',
                'province' => 'Jawa Timur',
                'regency' => 'Surabaya',
                'district' => 'Baya',
                'village' => 'Sura',
                'location' => 'Location 9',
                'toilet' => 1,
                'bedroom' => 3,
                'surface_area' => 500,
                'building_area' => 450,
                'carport' => 1,
                'floor' => 2,
                'description' => 'Description 9',
                'mosque' => true,
                'jogging' => false,
                'sports' => true,
                'child' => false,
                'pool' => false,
                'instalment' => 50000.00,
                'picture' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Property 10',
                'price' => 5500000.00,
                'category' => 'Commercial',
                'cluster_type' => 'Cluster E',
                'province' => 'Jawa Timur',
                'regency' => 'Surabaya',
                'district' => 'Baya',
                'village' => 'Sura',
                'location' => 'Location 10',
                'toilet' => 2,
                'bedroom' => 2,
                'surface_area' => 550,
                'building_area' => 500,
                'carport' => 2,
                'floor' => 1,
                'description' => 'Description 10',
                'mosque' => false,
                'jogging' => true,
                'sports' => false,
                'child' => true,
                'pool' => true,
                'instalment' => 55000.00,
                'picture' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            // Sixth pair with same province and district
            [
                'name' => 'Property 11',
                'price' => 600000.00,
                'category' => 'Residential',
                'cluster_type' => 'Cluster F',
                'province' => 'DKI Jakarta',
                'regency' => 'Jakarta Selatan',
                'district' => 'District 6',
                'village' => 'Village 6',
                'location' => 'Location 11',
                'toilet' => 3,
                'bedroom' => 4,
                'surface_area' => 600,
                'building_area' => 550,
                'carport' => 1,
                'floor' => 2,
                'description' => 'Description 11',
                'mosque' => true,
                'jogging' => false,
                'sports' => true,
                'child' => false,
                'pool' => false,
                'instalment' => 60000.00,
                'picture' => null,
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'name' => 'Property 12',
                'price' => 650000.00,
                'category' => 'Commercial',
                'cluster_type' => 'Cluster F',
                'province' => 'DKI Jakarta',
                'regency' => 'Jakarta Selatan',
                'district' => 'District 6',
                'village' => 'Village 6',
                'location' => 'Location 12',
                'toilet' => 2,
                'bedroom' => 3,
                'surface_area' => 650,
                'building_area' => 600,
                'carport' => 2,
                'floor' => 1,
                'description' => 'Description 12',
                'mosque' => false,
                'jogging' => true,
                'sports' => false,
                'child' => true,
                'pool' => true,
                'instalment' => 65000.00,
                'picture' => null,
                'created_at' => now(),
                'updated_at' => now()
            ]
        ];

        DB::table('properties')->insert($properties);
    }
}

 